include: .shared-ci.yml
variables:
  NAME: coupon-microservice

build-coupon-microservice:
  extends: .gradle-build

checkStyle-coupon-microservice:
  extends: .gradle-checkstyle

PMD-coupon-microservice:
  extends: .gradle-pmd

test-coupon-microservice:
  extends: .gradle-test