include: .shared-ci.yml

variables:
  NAME: cart-microservice

build-cart-microservice:
  extends: .gradle-build

checkStyle-cart-microservice:
  extends: .gradle-checkstyle

PMD-cart-microservice:
  extends: .gradle-pmd

test-cart-microservice:
  extends: .gradle-test
