include: .shared-ci.yml

variables:
  NAME: checkout-microservice

build-checkout-microservice:
  extends: .gradle-build

checkStyle-checkout-microservice:
  extends: .gradle-checkstyle

PMD-checkout-microservice:
  extends: .gradle-pmd

test-checkout-microservice:
  extends: .gradle-test