include: .shared-ci.yml

variables:
  NAME: customer-microservice

build-customer-microservice:
  extends: .gradle-build

checkStyle-customer-microservice:
  extends: .gradle-checkstyle

PMD-customer-microservice:
  extends: .gradle-pmd

test-customer-microservice:
  extends: .gradle-test