image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-customer-microservice:
  stage: build
  script:
    gradle customer-microservice:assemble customer-microservice:testClasses

checkStyle-customer-microservice:
  stage: staticAnalysis
  script:
    gradle customer-microservice:checkstyleMain customer-microservice:checkStyleTest
  allow_failure: true


PMD-customer-microservice:
  stage: staticAnalysis
  script:
    gradle customer-microservice:pmdMain
  allow_failure: true

test-customer-microservice:
  stage: test
  script:
    - gradle customer-microservice:test customer-microservice:jacocoTestReport
    - cat customer-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"
  coverage: /([0-9]{1,3})%/
